BitirmeProV3/BitirmeProV3/Controllers/ilanEklemeController.cs
using BitirmeProV3.Models;
using BitirmeProV3.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace BitirmeProV3.Controllers
{
    
    [Authorize]
    [ValidateInput(false)]
    public class ilanEklemeController : Controller
    {
        BitirmeProjesiDBEntities db = new BitirmeProjesiDBEntities();
        
        
        public IlanModel ekle(IlanModel model)
        {
            var ekle = db.TBL_Kategori.ToList();
            foreach (var item in ekle)
            {
                model.kategori.Add(item.KategoriAdi);
            }
            return model;
        }
    // GET: ilanEkleme
    public ActionResult Ilan()
        {
            IlanModel model = new IlanModel();
            
            return View(ekle(model));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ilan(IlanModel model, HttpPostedFileBase ilanResmi1, HttpPostedFileBase ilanResmi2, HttpPostedFileBase ilanResmi3)
        {
            var kullanici = User.Identity.Name;
            var kategori = db.TBL_Kategori.ToList();
            var sorgu = db.TBL_Kullanici.ToList();
            if (model.Ilan.KartBaslik==null)
            {
                ModelState.AddModelError("", "İlan Başlığı boş bırakılamaz.");
            }
            else
            {
                if (model.Ilan.KartBaslik.Length > 150)
                {
                    ModelState.AddModelError("", "İlan Başlığı 150 karakterden uzun olamaz");
                }
            }
            if (model.Ilan.KartAciklamasi==null)
            {
                ModelState.AddModelError("", "İlan Açıklaması boş bırakılamaz");
            }
            else
            {
                //if (model.Ilan.KartAciklamasi.Length > 1000)
                //{
                //    ModelState.AddModelError("", "İlan Açıklaması çok uzun");
                //}
            }
            
            
            if (model.ktgr== "Kategori")
            {
                ModelState.AddModelError("", "Kategori Seçilmedi");
            }

             if (ilanResmi1 != null)
                {
                    if (ilanResmi1.FileName.Length < 200)
                    {
                        string temp = Guid.NewGuid().ToString() + "_" + Path.GetFileName(ilanResmi1.FileName);
                        string filePath = Path.Combine(Server.MapPath("/Content/images/CardImages"), temp);
                        ilanResmi1.SaveAs(filePath);
                        model.Ilan.KartResim1 = "/Content/images/CardImages/" + temp;
                    }
                    else ModelState.AddModelError("", "Resim 1 Dosya Adi cok uzun");
                    {

                    }
                    
                }
                else
                {
                    ModelState.AddModelError("", "İlan Resmi 1 Boş Olmamalıdır.");
                }
                if (ilanResmi2 != null)
                {
                    if (ilanResmi2.FileName.Length < 200)
                    {
                        string temp = Guid.NewGuid().ToString() + "_" + Path.GetFileName(ilanResmi2.FileName);
                        string filePath = Path.Combine(Server.MapPath("/Content/images/CardImages"), temp);
                        ilanResmi2.SaveAs(filePath);
                        model.Ilan.KartResim2 = "/Content/images/CardImages/" + temp;
                    }
                    else
                    {
                        ModelState.AddModelError("", "Resim 2 Dosya Adi cok uzun");
                    }
                    
                }
                if (ilanResmi3 != null)
                {
                    if (ilanResmi3.FileName.Length < 200)
                    {
                        string temp = Guid.NewGuid().ToString() + "_" + Path.GetFileName(ilanResmi3.FileName);
                        string filePath = Path.Combine(Server.MapPath("/Content/images/CardImages"), temp);
                        ilanResmi3.SaveAs(filePath);
                        model.Ilan.KartResim3 = "/Content/images/CardImages/" + temp;
                    }
                    else
                    {
                        ModelState.AddModelError("", "Resim 3 Dosya Adi cok uzun");
                    }
                    
                }
            
            
            if (ModelState.IsValid==true)
            {
                foreach (var item in sorgu)
                {
                    if (kullanici == item.TBL_KullaniciOzellik.KullaniciAdi)
                    {
                        foreach (var ktgr in kategori)
                        {
                            if (model.ktgr == ktgr.KategoriAdi)
                            {
                                model.Ilan.KategoriID = ktgr.KategoriID;
                            }
                        }
                        model.Ilan.KullaniciID = item.KullaniciID;
                        if (model.yardim == true)
                        {
                            model.Ilan.AliciSatici = true;
                        }
                        else {
                            model.Ilan.AliciSatici = false;
                            if (model.Ilan.Fiyat == null)
                            {
                                ModelState.AddModelError("", "İlan Fiyatı Boş Olmamalıdır");
                            }
                        }
                        model.Ilan.Durum = true;
                        //item.TBL_IndexKart.Add(model.Ilan);
                        //item.TBL_IndexKart.Add(model.Ilan);
                        //db.TBL_IndexKart.Add(model.Ilan);
                        db.Entry(model.Ilan).State = EntityState.Added;
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index", "Main");
            }
            
                    return View(ekle(model));
        }
    }
}

BitirmeProV3/BitirmeProV3/Views/ilanEkleme/Ilan.cshtml
@model BitirmeProV3.Models.IlanModel
@{
    ViewBag.Title = "Ilan";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container h-100 login-page">
    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto h-100">
            <div class="jumbotron bg-light">
                @using (Html.BeginForm("Ilan", "ilanEkleme",null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Count() > 0)
                    {
                        <div class="alert alert-danger" role="alert">
                            @Html.ValidationSummary()
                        </div>

                    }
                    @Html.AntiForgeryToken()
                    <div class="form-group text-center">
                        <h3>İLAN VER</h3>
                    </div>

                    <div class="form-group">
                        <label for="IlanBaslik">İlan Başlığı</label>
                        @Html.TextBoxFor(i=>i.Ilan.KartBaslik,new {@class="form-control", id="IlanBaslik" ,placeholder="İlan Başlığı" })
                        
                    </div>
                    <div class="form-group">
                        <label for="summernote">İlan Açıklaması</label>
                        @Html.TextAreaFor(i => i.Ilan.KartAciklamasi, new { name = "textarea", @class="form-control", id="summernote",placeholder="İlan Açıklaması" ,cols="10", rows="5"})
                        
                    </div>
                    <hr>
                    <label class="d-block text-center" for="">En az 1 en fazla 3 adet resim Yükleyiniz</label>
                    <hr>
                    <div class="form-group">
                        <label for="İlanResmi1">İlan Resmi-1</label>
                        
                        <input type="file" class="form-control" name="ilanResmi1" id="ilanResmi1" accept="image/x-png,image/gif,image/jpeg">
                    </div>
                    <div class="form-group">
                        <label for="ilanResmi2">İlan Resmi-2</label>
                        <input type="file" class="form-control" id="ilanResmi2" name="ilanResmi2" accept="image/x-png,image/gif,image/jpeg">
                    </div>
                    <div class="form-group">
                        <label for="ilanResmi3">İlan Resmi-3</label>
                        <input type="file" class="form-control" id="ilanResmi3" name="ilanResmi3" accept="image/x-png,image/gif,image/jpeg">
                    </div>
                    <div class="form-group">
                        <hr>
                        <div class="container">
                            <label for="fiyat">Fiyatı giriniz eğer bu bir yardım ilanı ise kutucuğu işaretleyiniz</label>
                            <div class="row justify-content-start">
                                <div class="col-6">
                                    @Html.TextBoxFor(i=>i.Ilan.Fiyat,new{type="number",@class= "form-control fiyat",id="IlanFiyat",placeholder=100})
                                    @*<input type="number" class="form-control fiyat" id="IlanFiyat" placeholder="Fiyatı">*@

                                </div>
                                <div class="col-2">
                                    @Html.CheckBoxFor(i=>i.yardim,new { onclick = "document.getElementById('IlanFiyat').disabled=this.checked;", @class="form-control checkbox", id="IlanBaslik" })
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="form-group">
                        <label for="">Kategorisini Seçiniz</label>
                        @Html.DropDownListFor(i => i.ktgr,new SelectList(Model.kategori),"Kategori", new {@class="form-control w-50" })
                        @*<div class="dropdown">
                            <button type="button" class="btn btn-primary dropdown-toggle w-100" data-toggle="dropdown">
                                Dropdown button
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Link 1</a>
                                <a class="dropdown-item" href="#">Link 2</a>
                                <a class="dropdown-item" href="#">Link 3</a>
                            </div>
                        </div>*@
                    </div>


                    <div class="form-group text-center">
                        <button class="btn btn-success w-75 mt-3" type="submit" style="height: 50px;">YAYINLA</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>