BitirmeProV3/BitirmeProV3/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitirmeProV3.Models;
using BitirmeProV3.Models.Entity;

namespace BitirmeProV3.Controllers
{
    
    public class MainController : Controller
    {
        // GET: Main
        BitirmeProjesiDBEntities db = new BitirmeProjesiDBEntities();
        public ActionResult Index()
        {
            var Kategori = db.TBL_Kategori.ToList();
            var IndexCard = db.TBL_IndexKart.ToList();
            
            KategoriCardModel model = new KategoriCardModel();
            model.Kategoris = Kategori;
            model.IndexKarts = IndexCard;
            return View(model);
        }
        public ActionResult Kategori(int id)
        {
            KategoriCardModel model = new KategoriCardModel();
            var Kategori = db.TBL_Kategori.ToList();
            var IndexCard = db.TBL_IndexKart.ToList();
            if (id==-1)
            {
                foreach (var item in IndexCard)
                {
                    if (true == item.AliciSatici)
                    {
                        model.filtre.Add(item);

                    }
                }
            }
            else
            {
                foreach (var item in IndexCard)
                {
                    if (id == item.TBL_Kategori.KategoriID)
                    {
                        model.filtre.Add(item);

                    }
                }
            }
            
            model.Kategoris = Kategori;
            model.IndexKarts = model.filtre;

            return View("~/Views/Main/Index.cshtml",model);
        }
        public ActionResult Getimage()
        {
            
            var sorgu = db.TBL_Kullanici.ToList();
            foreach (var item in sorgu)
            {
                if (User.Identity.Name == item.TBL_KullaniciOzellik.KullaniciAdi)
                {
                    
                    return Content(item.TBL_KullaniciOzellik.ProfilResmi);
                }
            }
            return Content(null);
        }

    }
}

BitirmeProV3/BitirmeProV3/Views/Main/Index.cshtml
@using BitirmeProV3.Models;
@model KategoriCardModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container p-5 my-5">
    <div class="row d-block">
        <div class="jumbotron bg-jumbotron-img">
            <h1 class="display-4 text-dark">USTAM.COM</h1>
            <p class="lead text-dark">
                USTAM.COM yetenekli freelancer'ların kendilerine uygun işletmeler ve girişimlerle
                buluştuğu, topluluk mantığıyla ​i​şleyen ​​özgürlükçü bir çalışma platformudur.
            </p>
        </div>
    </div>
    <div class="row mb-3">
        @Html.Partial("Kategori",Model.Kategoris)
    </div>
    <div class="row ">
       @Html.Partial("IndexCard",Model.IndexKarts)
        
       
        <div class="w-100"></div>
    </div>


</div>
<div class="d-flex justify-content-center">
    <button class="btn btn-light">
        <
    </button> <button class="btn btn-light">
        1
    </button>
    <button class="btn btn-light">2</button>
    <button class="btn btn-light">3</button>
    <button class="btn btn-light">></button>
</div>

BitirmeProV3/BitirmeProV3/Views/Main/IndexCard.cshtml
@using BitirmeProV3.Models.Entity;
@model List<TBL_IndexKart>

@* Listeyi Ters çevirdik AsEnumerable *@
@foreach (var card in Model.AsEnumerable().Reverse())
{
    if (card.Durum == true)
    {
        <div class="col-md-3 mb-3">

            <div class="card ">
                <a style=" max-height:250px;" href='@Url.Action("CardPage","CardPage",new {id=card.IndexKartID})'><img class="card-img-top" style="height:236px;" src="@card.KartResim1" alt=""></a>
                <div class=" d-inline-block m-1">
                    <div class="">
                        <div>
                            <a class="" href='@Url.Action("Profil","Profil",new {kullaniciAdi=card.TBL_Kullanici.TBL_KullaniciOzellik.KullaniciAdi })'>
                                <img class="float-left rounded-circle"
                                     src="@card.TBL_Kullanici.TBL_KullaniciOzellik.ProfilResmi" href='@Url.Action("Profil","Profil",new {kullaniciAdi=card.TBL_Kullanici.TBL_KullaniciOzellik.KullaniciAdi })' style="width:38px; height:38px;" alt="">
                            </a>
                        </div>
                        <div class="d-inline-block ml-1" style="height: 36px;">
                            <div>

                                <a class="text-dark d-block font-weight-bold" style="font-size:14px" id="link" href='@Url.Action("Profil","Profil",new {kullaniciAdi=card.TBL_Kullanici.TBL_KullaniciOzellik.KullaniciAdi })' name="link" value="Profil">
                                    @card.TBL_Kullanici.TBL_KullaniciOzellik.KullaniciAdi
                                </a>
                            </div>
                            <div>
                                <p style="font-size:12px">@card.TBL_Kullanici.TBL_KullaniciOzellik.Unvani</p>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card-body pt-1">
                    <div class="card-text " style="height:90px">
                        @if (card.KartBaslik.Length > 90)
                        {
                            @Html.Raw(card.KartBaslik.Substring(0, 80));

                            <span>...</span>
                        }
                        else
                        {
                            @Html.Raw(card.KartBaslik)
                        }
                    </div>
                    
                </div>
                @if (false == card.AliciSatici)
                {
                    <div class="row justify-content-end mb-2 mr-3">
                        <div class="row">
                            <div class="col-sm-4">
                                <a href='@Url.Action("CardPage","CardPage",new {id=card.IndexKartID})' class="btn btn-outline-primary">@card.Fiyat<span>TL</span></a>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="row justify-content-end mb-2 mr-3">
                        <div class="row">
                            <div class="col-sm-4">
                                <a href='@Url.Action("CardPage","CardPage",new {id=card.IndexKartID})' class="btn btn-outline-success">YARDIM</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
            @*}*@
        </div>
    }





}

BitirmeProV3/BitirmeProV3/Views/Main/Kategori.cshtml
@using BitirmeProV3.Models.Entity
@model List<TBL_Kategori>



@foreach (var ktgr in Model)
{
    <a class="col border radius btn btn-outline-danger stretched-link ml-1" href="@Url.Action("Kategori","Main",new {id=ktgr.KategoriID })">@ktgr.KategoriAdi</a>
    if (ktgr.KategoriID == 4)
    {
        break;
    }
}
<div class="dropdown dropdown-menu-down">
    <a class="col border radius btn btn-outline-danger stretched-link ml-1 dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Kategoriler
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        @foreach (var ktgr in Model)
        {
            <a class="col border radius btn btn-outline-danger stretched-link p-2" href="@Url.Action("Kategori","Main",new {id=ktgr.KategoriID })">@ktgr.KategoriAdi</a>
        }
    </div>
</div>
<a class="btn btn-outline-success ml-2" href="@Url.Action("Kategori","Main",new {id=-1 })">YARDIM</a>